OWASP.Top10/Controllers/BrokenAuthenticationController.cs
using OWASP.Top10.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace OWASP.Top10.Controllers
{
    public class BrokenAuthenticationController : BaseController
    {
        public ActionResult Login()
        {
            return View(new LoginViewModel
            {
                Username = "anishantha87@gmail.com",
                Password = "123456"
            });
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            FormsAuthentication.SetAuthCookie(username, false);

            HttpCookie userInfo = new HttpCookie("userInfo");
            //userInfo.Secure = true;
            //userInfo.HttpOnly = true;
            //userInfo.sa
            userInfo["UserName"] = username;
            userInfo["IsAdmin"] = "false";
            userInfo["Test"] = "1";
            userInfo.Expires.Add(new TimeSpan(1, 0, 0));
            Response.Cookies.Add(userInfo);

            return RedirectToAction("UserInformation");
        }

        [HttpGet]
        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            this.ControllerContext.HttpContext.Response.Cookies.Clear();

            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult UserInformation()
        {
            var cookie = Request.Cookies["userInfo"];
            if (cookie != null)
            {
                bool.TryParse(cookie["IsAdmin"], out bool isAdmin);

                ViewBag.IsAdmin = isAdmin;
            }
            return View();
        }

    }
}

OWASP.Top10/Controllers/CrossSiteScriptingController.cs
using OWASP.Top10.Helpers;
using OWASP.Top10.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace OWASP.Top10.Controllers
{
    public class CrossSiteScriptingController : BaseController
    {
        // GET: CrossSiteScripting
        public ActionResult Index()
        {
            var list = new List<CommentViewModel>();
            var dt = DbHelper.ExecuteSelectCommand("select * from comment");
            foreach (DataRow item in dt.Rows)
            {
                list.Add(new CommentViewModel { Comment = item["comment"].ToString() });
            }
            return View(list);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Index(string searchQuery = "")
        {
            if (!string.IsNullOrEmpty(searchQuery))
            {
                DbHelper.ExecuteInsertCommand("Insert into comment(comment) values ('" + searchQuery + "')");
            }

            var dt = DbHelper.ExecuteSelectCommand("select * from comment");
            var list = new List<CommentViewModel>();

            foreach (DataRow item in dt.Rows)
            {
                list.Add(new CommentViewModel { Comment = item["comment"].ToString() });
            }
            return View(list);
        }


        [ValidateInput(false)]
        public ActionResult Get(string firstName, string email)
        {
            ViewBag.FirstName = firstName;
            ViewBag.Email = email;

            return View();
        }

        public ActionResult Comments()
        {
            var list = new List<CommentViewModel>();
            var dt = DbHelper.ExecuteSelectCommand("select * from comment");
            foreach (DataRow item in dt.Rows)
            {
                list.Add(new CommentViewModel
                {
                    Comment = item["comment"].ToString(),
                    InsertedOn = ((DateTime)item["InsertedOn"]).ToLongDateString()
                });
            }
            return View(list);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Comments(string searchQuery = "")
        {
            if (!string.IsNullOrEmpty(searchQuery))
            {
                DbHelper.ExecuteInsertCommand("Insert into comment(comment) values ('" + searchQuery + "')");
            }

            var dt = DbHelper.ExecuteSelectCommand("select * from comment");
            var list = new List<CommentViewModel>();

            foreach (DataRow item in dt.Rows)
            {
                list.Add(new CommentViewModel
                {
                    Comment = item["comment"].ToString(),
                    InsertedOn = ((DateTime)item["InsertedOn"]).ToLongDateString()
                });
            }
            return View(list);
        }
    }
}

OWASP.Top10/Controllers/HomeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OWASP.Top10.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            HttpCookie cookie = new HttpCookie("CEG.Secutity.Identity");
            cookie["ApplicationName"] = "Cyber Security Training";
            cookie["HostedBy"] = "Security CEG";
            cookie["User"] = JsonConvert.SerializeObject(new { FirstName = "Aruna", LastName = "Perera" });
            Response.Cookies.Add(cookie);
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

OWASP.Top10/Controllers/InjectionController.cs
using OWASP.Top10.Helpers;
using OWASP.Top10.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OWASP.Top10.Controllers
{
    public class InjectionController : BaseController
    {
        // GET: Injection
        public ActionResult Index()
        {
            var dt = DbHelper.ExecuteSelectCommand("select customer_id,first_Name, last_Name,email, last_update from customer order by first_name limit 20;");
            var list = new List<CustomerViewModel>();

            foreach (DataRow row in dt.Rows)
            {
                list.Add(new CustomerViewModel
                {
                    FirstName = row["first_Name"].ToString(),
                    LastName = row["last_Name"].ToString(),
                    Email = row["email"].ToString()
                });
            }
            ViewBag.RowCount = list.Count();
            return View(list);
        }

        [HttpPost]
        public ActionResult Index(string searchQuery)
        {
            string query = $"select customer_id,first_Name, last_Name,email, last_update from customer where first_name like '%{searchQuery}%';";
            var dt = DbHelper.ExecuteSelectCommand(query);
            var list = new List<CustomerViewModel>();

            foreach (DataRow row in dt.Rows)
            {
                list.Add(new CustomerViewModel
                {
                    FirstName = row["first_Name"].ToString(),
                    LastName = row["last_Name"].ToString(),
                    Email = row["email"].ToString()
                });
            }

            ViewBag.RowCount = list.Count();
            return View(list);
        }
    }
}

OWASP.Top10/Controllers/LoginController.cs
using OWASP.Top10.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OWASP.Top10.Controllers
{
    public class LoginController : BaseController
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
                return View();

            //HttpCookie cookie = new HttpCookie("CEG.Secutity.Identity");
            //cookie["ApplicationName"] = "Cyber Security Training";
            //cookie["HostedBy"] = "Security CEG";
            //cookie["User"]  = JsonConvert.SerializeObject(model);

            //Response.Cookies.Add(cookie);

            return RedirectToAction("Index", "Home");
        }
    }
}

OWASP.Top10/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OWASP.Top10/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OWASP.Top10/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<style>
    ol {
        font-size: larger;
    }
</style>

<div class="jumbotron">
    <h1>OWASP Top 10 Demonstration</h1>
    <p class="lead">Prepared for Security CEG to provide better understanding of vulnerability causes by Aruna Perera.</p>
    <p><a href="https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf.pdf" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
@*@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <input type="text" name="name" value="" />
}*@
<div class="row">
    <div class="col-md-12">
        <ol>
            <li>
                <h3>Injection</h3>
                <p>
                    SQL injection, LDAP injection, and CRLF injection, occur when an attacker sends untrusted data to an interpreter that is executed as a command without proper authorization.
                </p>
                <p>
                    @Html.ActionLink("Learn more", "Index", "Injection", null, new { @class = "btn btn-default" })
                </p>
            </li>
            <li>
                <h3>Broken Authentication</h3>
                <p>
                    Credential stuffing, the use of lists of known passwords, is a common attack.
                    Most authentication attacks occur due to the continued use of passwords as a sole factor.
                    Application session timeouts aren’t set properly. A user uses a public computer to access an application
                </p>
                <p>@Html.ActionLink("Learn more", "Login", "BrokenAuthentication", null, new { @class = "btn btn-default" })</p>
            </li>
            <li>
                <h3>Sensitive Data Exposure</h3>
                <p>
                    An application encrypts credit card numbers in a database using automatic database encryption.
                    A site doesn't use or enforce TLS for all pages or supports weak encryption.
                    : The password database uses unsalted or simple hashes to store everyone's passwords.
                </p>
                <p>
                    @Html.ActionLink("Learn more", "Index", "SensitiveDataExposure", null, new { @class = "btn btn-default" })

                </p>
            </li>
            <li>
                <h3>XML External Entities (XXE)</h3>
                <p>
                    Poorly configured XML processors evaluate external entity references within XML documents. Attackers can use external entities for attacks including remote code execution, and to disclose internal files and SMB file shares.
                </p>
                <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
            </li>
            <li>
                <h3>Broken Access Control</h3>
                <p>
                    Improperly configured or missing restrictions on authenticated users allow them to access unauthorized functionality or data, such as accessing other users’ accounts, viewing sensitive documents, and modifying data and access rights.
                </p>
                <p>  @Html.ActionLink("Learn more", "Index", "SecurityMisconfiguration", null, new { @class = "btn btn-default" })</p>
            </li>
            <li>
                <h3>Security Misconfiguration</h3>
                <p>
                    This risk refers to improper implementation of controls intended to keep application data safe, such as misconfiguration of security headers, error messages containing sensitive information (information leakage), and not patching or upgrading systems, frameworks, and components.
                </p>
                <p>  @Html.ActionLink("Learn more", "Index", "SecurityMisconfiguration", null, new { @class = "btn btn-default" })</p>

            </li>
            <li>
                <h3>Cross-Site Scripting (XSS)</h3>
                <p>
                    Cross-site scripting (XSS) flaws give attackers the capability to inject client-side scripts into the application, for example, to redirect users to malicious websites.
                </p>
                <p>  @Html.ActionLink("Learn more", "Index", "CrossSiteScripting", null, new { @class = "btn btn-default" })</p>
            </li>
            <li>
                <h3>Insecure Deserialization</h3>
                <p>
                    Insecure deserialization flaws can enable an attacker to execute code in the application remotely, tamper or delete serialized (written to disk) objects, conduct injection attacks, and elevate privileges.
                </p>
                <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
            </li>
            <li>
                <h3>Using Components with Known Vulnerabilities</h3>
                <p>
                    Developers frequently don’t know which open source and third-party components are in their applications, making it difficult to update components when new vulnerabilities are discovered. Attackers can exploit an insecure component to take over the server or steal sensitive data.
                </p>
                <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
            </li>
            <li>
                <h3>Insufficient Logging & Monitoring</h3>
                <p>
                    The time to detect a breach is frequently measured in weeks or months. Insufficient logging and ineffective integration with security incident response systems allow attackers to pivot to other systems and maintain persistent threats.
                </p>
                <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
            </li>
        </ol>
    </div>
</div>